### PR TITLE
Upgrade dependencies to more recent ones.

### PR DESCRIPTION
**Pull request by jycr**
Can't upgrade bytebuddy to last release because MethodDelegation.toInstanceField has been removed

### CODE REVIEW

**Comment by zapodot** [comment]
Thanks @jycr :+1:! I will have a look at your changes pretty soon

**Comment by zapodot** [comment]
@jycr this PR can currently not be merged as it breaks the Java 7 build, most likely because some of the dependencies require Java 8 for the version you upgraded to. It would be great if you could have a look and change to Java 7 - compatible versions

**Comment by zapodot** [comment]
Hi @jycr! Just made the updates myself. Thanks anyway for your contribution :+1:

**Comment by jycr** [comment]
You're welcome:)

Is it possible to upgrade Guava to 22.0?

Because older versions conflict with the one I use in my projects

**Comment by zapodot** [comment]
Sorry.. The last version that is compatible with Java 7 is 20.0.

If you need a newer version in your project that really should not be a
problem. Just add Guava as a dependency to your project and it should work
just fine.



24. jun. 2017 10.00 p.m. skrev "JY Cr" <notifications@github.com>:

**Comment by jycr** [comment]
You use com.google.common.net.HostAndPort.getHostText() which is deprecated in v20.0 but removed in v22.0
So, i can use v22.0 in my project with embedded-ldap-junit

**Comment by zapodot** [comment]
@jycr I did try to build the project on an Java 8 JDK using Guava 22 and did not find any trouble building or running the tests in the project due to a missing reference to the method you mentioned.
However, while updating the dependency to 22.0 some of the tests will fail as the new Guava version references java.util.Function which was introduced in Java 8. I.e moving to Guava 8 would mean that the Java baseline for the embedded-ldap-junit library would have to Java 8 leaving it usesless for Java 7 users.

At some point in the future that is surely going to happen, but not as this point. As I did not find any references to the deprecated/obsolete com.google.common.net.HostAndPort.getHostText() method in the project, it should actually work well with Guava 22.

**Pull request closed without merging**
