### PR TITLE
Allow test to specify listener

### PR DESCRIPTION
**Pull request by reftel**
This permits things like enabling starttls support.

### CODE REVIEW

**Comment by reftel** [comment]
It appears the Travis builds fail due to `install-jdk.sh` no longer supporting Java 8. See PR #44 for a fix.

**Comment by zapodot** [comment]
@reftel I have merged #44 now, so please rebase and try again ;-)

Thank you for contributing

**Comment by reftel** [comment]
Rebased to master.

**Comment by reftel** [comment]
@zapodot Any more comments?

**Comment by zapodot** [comment]
Looks better now @reftel 👍  
Thanks again!

**Comment by zapodot** [comment]
@reftel Just released v. 0.8 that includes your fix to Maven central

**Comment by reftel** [comment]
Takk! =)

**Pull request merged**
